@CS2TeamManager.Api_HostAddress = https://localhost:7185

### REGISTER
POST {{CS2TeamManager.Api_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "username": "NikoCS2",
  "email": "niko@cs2.com",
  "password": "Password123!"
}



### LOGIN (automatically get token)
# @name login
POST {{CS2TeamManager.Api_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "email": "niko@cs2.com",
  "password": "Password123!"
}

### team creation
POST {{CS2TeamManager.Api_HostAddress}}/api/Teams
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "name": "Novi CS2 Tim",
  "description": "Opis mog tima"
}

### get teams
GET {{CS2TeamManager.Api_HostAddress}}/api/Teams/my-teams
Authorization: Bearer {{login.response.body.$.token}}

### PLAYER REGISTRY
POST {{CS2TeamManager.Api_HostAddress}}/api/Auth/register
Content-Type: application/json

{
  "username": "S1mple",
  "email": "s1mple@cs2.com",
  "password": "Password123!"
}

### ADDING PLAYERS TO A TEAM
POST {{CS2TeamManager.Api_HostAddress}}/api/Teams/1/members
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "userEmail": "s1mple@cs2.com"
}

### ADD A NEW MATCH (FOR TEAM 1)
POST {{CS2TeamManager.Api_HostAddress}}/api/Matches/1
Content-Type: application/json
Authorization: Bearer {{login.response.body.$.token}}

{
  "opponentName": "G2 Esports",
  "tournament": "ESL Pro League",
  "scheduledDate": "2026-03-02T18:00:00Z",
  "playedDate": "2026-03-02T20:00:00Z",
  "status": 2, 
  "ourScore": 13,
  "opponentScore": 10,
  "bestOf": 3,
  "maps": ["Mirage", "Inferno"],
  "notes": "Sunpayus destroyed us on the first map but we came back"
}

### GET ALL MATCHES FOR TEAM 1
GET {{CS2TeamManager.Api_HostAddress}}/api/Matches/1
Authorization: Bearer {{login.response.body.$.token}}
